apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: advanced
  namespace: 0oqfemca-expose-advanced-dev
  annotations:
    # Eliminamos cualquier valor previo y luego ponemos none
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_clear_headers "X-Frame-Options";
      more_set_headers "X-Frame-Options: none";
spec:
  rules:
    - host: backend-expose-advanced-0oqfemca-expose-advanced-dev.development.krci-dev.cloudmentor.academy
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: root-service
                port:
                  number: 80
          - path: /api/hello
            pathType: Prefix
            backend:
              service:
                name: hello-service
                port:
                  number: 80
